version: '3.4'

services:
  halofinlandbot:
    image: halofinlandbot
    env_file: ./environment/.env
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    restart: unless-stopped
